pull_request_rules:
  - name: Automatic merge to master on successful build if it's not WIP
    conditions:
      - base=master
      - check-success=build
      - check-success=test
      - -title~=(?i)wip
    actions:
      merge:
        method: merge
      assign:
        add_users:
          - 5h15h4k1n9
  - name: Add `java` label, if files associated with Kotlin were changed
    conditions:
      - and:
        - files~=\.java$
    actions:
      label:
        add:
          - java
  - name: Add `config` label, if files associated with configs were changed
    conditions:
      - or:
        - files~=\.yml$
        - files~=\.yaml$
        - files~=\.properties$
        - files~=\.xml$
        - files~=\.json$
        - files~=\.ini$
        - files~=\.conf$
        - files~=\.cfg$
        - files~=\.toml$
    actions:
      label:
        add:
          - config