name: Build
on:
  pull_request:
    branches: [ master ]
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          java-package: jdk
          architecture: x64
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Test with Maven
        run: ./mvnw test
      - name: Show test results
        uses: mikepenz/action-junit-report@v2
        with:
          files: target/surefire-reports/TEST-*.xml
